# Orthox-64 Limine Config
timeout: 3

/Orthox-64 v0.6.0
    protocol: limine
    path: boot():/boot/kernel.elf

    # ユーザープログラムをロード
    module_path: boot():/boot/sh.elf
    module_path: boot():/boot/rootfs.img
