# Orthox-64 カーネル ネイティブビルド Makefile
#
# **ソース一覧は host の Makefile の X86_64_SRCS / SYSCALL_SRCS / CORE_SRCS と
# 同じものを並べる (2026-09-12 に合わせ直した)。**3 アーキ統合で x86 のファイルが
# kernel/x86_64/ へ移ったのに、ここは平坦な kernel/ のままだった。そのため
# OS 内ビルドは「No rule to make target '/kbuild/kernel/init.o'」で止まり、
# x86-kernel-smoke の kernel-native-build: PASS が出せない状態が続いていた。
# Orthox-64 上で実行: make -f /src/kernel-build/Makefile

SRCDIR  ?= /src/kernel-build
BUILD   ?= /kbuild
OUTPUT  ?= /kernel.elf

# /bin/sh は user/sh.elf（カスタム最小シェル）のため for ループが使えない。
# busybox ash を明示的に指定する。
SHELL = /bin/ash

CC1 = /bin/cc1
AS  = /bin/as
LD  = /bin/ld

# -DLWIP_NOASSERT: abort() 依存を除去（カーネル環境では assert 不要）
CC1FLAGS = \
    -quiet -nostdinc \
    -std=c11 -ffreestanding -fno-stack-protector -fno-stack-check \
    -fno-lto -fno-PIE -mno-80387 -mno-mmx -mno-sse -mno-sse2 \
    -mno-red-zone -mcmodel=kernel -O2 \
    -DLWIP_NOASSERT \
    -I$(SRCDIR)/include \
    -I$(SRCDIR)/ports/lwip/src/include \
    -I/usr/include

KERNEL_LDFLAGS = -nostdlib -static -T $(SRCDIR)/scripts/kernel.ld

KERNEL_C_SRCS = \
    kernel/x86_64/init.c kernel/x86_64/kassert.c kernel/x86_64/pmm.c \
    kernel/x86_64/gdt.c kernel/x86_64/vmm.c kernel/x86_64/idt.c \
    kernel/x86_64/lapic.c kernel/x86_64/pic.c kernel/x86_64/smp.c \
    kernel/x86_64/spinlock.c kernel/x86_64/keyboard.c kernel/x86_64/pci.c \
    kernel/x86_64/sound.c kernel/x86_64/uname.c kernel/x86_64/rng.c \
    kernel/x86_64/pcstat.c kernel/x86_64/sys_vm.c kernel/x86_64/sys_time.c \
    kernel/x86_64/sys_device.c kernel/x86_64/syscall_msr.c \
    kernel/x86_64/virtio.c kernel/x86_64/virtio_net.c kernel/x86_64/virtio_blk.c \
    kernel/syscall.c kernel/sys_trace.c kernel/sys_signal.c \
    kernel/sys_proc.c kernel/sys_fs.c kernel/sys_random.c kernel/sys_net.c \
    kernel/sys_rlimit.c kernel/sys_uname.c kernel/sys_task.c kernel/sys_iov.c \
    kernel/sys_access.c \
    kernel/sys_lseek.c \
    kernel/sys_tty.c \
    kernel/irq.c kernel/bottom_half.c \
    kernel/elf.c kernel/task.c kernel/task_exec.c kernel/task_fork.c \
    kernel/sys_mmap.c kernel/vm_cow.c kernel/sched.c kernel/wait.c kernel/fs.c kernel/vfs.c \
    kernel/storage.c kernel/xv6bio.c kernel/xv6log.c kernel/xv6fs.c \
    kernel/net.c kernel/net_socket.c kernel/lwip_port.c \
    kernel/cstring.c kernel/cstdio.c kernel/cstdlib.c kernel/usb.c

KERNEL_S_SRCS = \
    kernel/x86_64/gdt_flush.S \
    kernel/x86_64/interrupt.S \
    kernel/x86_64/syscall_entry.S \
    kernel/x86_64/task_switch.S

LWIP_SRCS = \
    ports/lwip/src/core/def.c \
    ports/lwip/src/core/dns.c \
    ports/lwip/src/core/inet_chksum.c \
    ports/lwip/src/core/init.c \
    ports/lwip/src/core/ip.c \
    ports/lwip/src/core/mem.c \
    ports/lwip/src/core/memp.c \
    ports/lwip/src/core/netif.c \
    ports/lwip/src/core/pbuf.c \
    ports/lwip/src/core/raw.c \
    ports/lwip/src/core/stats.c \
    ports/lwip/src/core/sys.c \
    ports/lwip/src/core/tcp.c \
    ports/lwip/src/core/tcp_in.c \
    ports/lwip/src/core/tcp_out.c \
    ports/lwip/src/core/timeouts.c \
    ports/lwip/src/core/udp.c \
    ports/lwip/src/core/ipv4/dhcp.c \
    ports/lwip/src/core/ipv4/etharp.c \
    ports/lwip/src/core/ipv4/icmp.c \
    ports/lwip/src/core/ipv4/ip4.c \
    ports/lwip/src/core/ipv4/ip4_addr.c \
    ports/lwip/src/netif/ethernet.c

KERNEL_OBJS = \
    $(patsubst kernel/%.c,   $(BUILD)/kernel/%.o, $(KERNEL_C_SRCS)) \
    $(patsubst kernel/%.S,   $(BUILD)/kernel/%.o, $(KERNEL_S_SRCS)) \
    $(patsubst ports/lwip/src/%.c, $(BUILD)/lwip/%.o, $(LWIP_SRCS))

# ビルドディレクトリ (/kbuild/**) はホスト側 rootfs ビルド時に事前作成済み（rootfs/kbuild/）。
# xv6fs 上に永続化することで2回目以降はインクリメンタルビルドになる。

.PHONY: all clean

all: $(OUTPUT)
	@echo kernel-native-build: PASS

$(OUTPUT): $(KERNEL_OBJS)
	$(LD) $(KERNEL_LDFLAGS) $(KERNEL_OBJS) -o $@

$(BUILD)/kernel/%.o: $(SRCDIR)/kernel/%.c
	$(CC1) $(CC1FLAGS) $< -o $(BUILD)/kernel/$*.s
	$(AS) $(BUILD)/kernel/$*.s -o $@
	@rm -f $(BUILD)/kernel/$*.s

$(BUILD)/kernel/%.o: $(SRCDIR)/kernel/%.S
	$(AS) $< -o $@

$(BUILD)/lwip/%.o: $(SRCDIR)/ports/lwip/src/%.c
	$(CC1) $(CC1FLAGS) $< -o $(BUILD)/lwip/$*.s
	$(AS) $(BUILD)/lwip/$*.s -o $@
	@rm -f $(BUILD)/lwip/$*.s

clean:
	rm -rf $(BUILD) $(OUTPUT)
